# models
# EPOCHS = 300
EPOCHS = 3
VALIDATION_SPLIT = 0.2
DATASETS_SPLIT = 0.8

ONLY_PREPROCESS_DATA = False
USE_MEMORY_FEATURE = True
CREATE_PIECEWISE_LINEAR_CPU_MODEL = False
PIECEWISE_LINEAR_CPU_MODELS_COUNT = 3

# datset
CPU_FEATURE_NAME = 'cpu'
CPU_FEATURE_UNIT = 'CPUs'

MEMORY_FEATURE_NAME = 'memory'
MEMORY_FEATURE_UNIT = 'KiB'

LABEL_NAME = 'power_draw'
LABEL_UNIT = 'kWh'
